# Generated by Django 4.0 on 2022-02-21 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='device',
            name='ven_id',
            field=models.CharField(max_length=80),
        ),
    ]
