# Generated by Django 3.2.13 on 2022-05-16 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_alter_device_device_id_alter_device_ven_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='registerConsumed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='device',
            name='registerProduced',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('device_id', 'ven_id')},
        ),
    ]
