# Generated by Django 3.2.13 on 2022-06-01 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ven', '0001_initial'),
        ('devices', '0003_auto_20220516_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='ven_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ven.ven'),
        ),
    ]
