# Generated by Django 3.2.13 on 2022-06-01 04:20

from django.db import migrations


def devices_link_ven(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Devices = apps.get_model('devices', 'Device')
    VEN = apps.get_model('ven', 'VEN')
    for device in Devices.objects.all():
        ven = VEN(ven_id=device.ven_id)
        ven.save()
        device.ven_id = ven 
        device.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ven', '0001_initial'),
        ('devices', '0004_alter_device_ven_id'),
    ]

    operations = [
        migrations.RunPython(devices_link_ven),

    ]

