# Generated by Django 3.2.13 on 2022-06-03 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ven', '0008_alter_ven_token'),
        ('devices', '0006_rename_ven_id_device_ven'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('device_id', 'ven_id')},
        ),
    ]
