# Generated by Django 3.2.13 on 2022-06-08 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ven', '0009_auto_20220608_2310'),
        ('devices', '0007_alter_device_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('device_id', 'ven')},
        ),
    ]
