# Generated by Django 3.2.13 on 2022-06-08 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ven', '0011_alter_ven_token'),
        ('devices', '0008_alter_device_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='ven',
            new_name='ven_id',
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('device_id', 'ven_id')},
        ),
    ]
