# Generated by Django 3.2.13 on 2022-06-08 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ven', '0012_alter_ven_token'),
        ('devices', '0009_auto_20220608_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='ven_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='ven.ven'),
        ),
    ]
