# Generated by Django 3.2.13 on 2022-06-20 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ven', '0015_alter_ven_token'),
        ('devices', '0010_alter_device_ven_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='ven_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ven.ven'),
        ),
    ]
