# Generated by Django 3.2.13 on 2022-06-01 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ven', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ven',
            name='token',
            field=models.CharField(default='8K6CSXKJ', max_length=80),
        ),
    ]
