# Generated by Django 3.2.13 on 2022-06-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ven', '0005_alter_ven_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ven',
            name='token',
            field=models.CharField(default='YKBD2V28', max_length=80),
        ),
    ]
