# Generated by Django 3.2.13 on 2022-06-08 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ven', '0008_alter_ven_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ven',
            name='ven_id',
        ),
        migrations.AlterField(
            model_name='ven',
            name='id',
            field=models.CharField(max_length=80, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ven',
            name='token',
            field=models.CharField(default='JL3J57H2', max_length=80),
        ),
    ]
