# Generated by Django 3.2.13 on 2022-06-08 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ven', '0009_auto_20220608_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ven',
            name='token',
            field=models.CharField(default='ZP6P7LRI', max_length=80),
        ),
    ]
