# Generated by Django 3.2.13 on 2022-06-08 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ven', '0011_alter_ven_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ven',
            name='token',
            field=models.CharField(default='XHK78QUT', max_length=80),
        ),
    ]
