# Generated by Django 3.2.13 on 2022-06-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ven', '0012_alter_ven_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ven',
            name='token',
            field=models.CharField(default='Y6LE5TC3', max_length=80),
        ),
    ]
