# Generated by Django 3.2.13 on 2022-06-09 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ven', '0013_alter_ven_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ven',
            name='token',
            field=models.CharField(default='H2WEPFSO', max_length=80),
        ),
    ]
