# Generated by Django 4.0 on 2022-02-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_type', models.CharField(max_length=250)),
                ('member_name', models.CharField(max_length=250)),
                ('account_address', models.CharField(max_length=250)),
                ('account_number', models.CharField(max_length=250)),
                ('member_email', models.CharField(max_length=250)),
                ('member_phone', models.CharField(max_length=250)),
                ('ven_id', models.CharField(max_length=250)),
                ('device_id', models.CharField(max_length=250)),
                ('device_type', models.CharField(max_length=250)),
                ('company', models.CharField(blank=True, max_length=250)),
                ('aggregator_name', models.CharField(blank=True, max_length=250)),
                ('aggregator_email', models.CharField(blank=True, max_length=250)),
                ('aggregator_phone', models.CharField(blank=True, max_length=250)),
            ],
        ),
    ]
